{{- if .Values.context-engine.enabled }}
##########################################################################
# Knowledge Service — ServiceAccount
##########################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-context-engine-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "athena.labels" . | nindent 4 }}
    app.kubernetes.io/component: context-engine
  annotations:
    azure.workload.identity/client-id: {{ .Values.context-engine.managedIdentity.clientId | quote }}
automountServiceAccountToken: false
{{- end }}
