{{- if .Values.inference.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-inference-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "enterprise-slm.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
  annotations:
    azure.workload.identity/client-id: {{ .Values.inference.managedIdentity.clientId | quote }}
automountServiceAccountToken: false
{{- end }}
