{{- if .Values.inference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "athena.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
spec:
  type: {{ .Values.inference.service.type }}
  selector:
    app.kubernetes.io/component: inference
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.inference.service.port }}
      targetPort: {{ .Values.inference.service.targetPort }}
      protocol: TCP
{{- end }}
